version: '3.8'

services:
  db:
    image: postgres:15
    container_name: heart_disease_db_postgres
    environment:
      POSTGRES_DB: heartdiseasedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    depends_on:
      - db

volumes:
  pgdata:
